### PR TITLE
check data overwrite

### PR DESCRIPTION
**Pull request by hmmr**
Check if the data can be overwritten.

### CODE REVIEW

**Comment by javajolt** [comment]
@hmmr Can we work on breaking this test up?  Or at least create a second test with the sole purpose of overwriting data?

**Comment by hmmr** [comment]
I will create a separate test module, just for that (but, having it also included in ts_mighty_basic wouldn't hurt).

**Comment by javajolt** [comment]
Let's get it in so we at least have test coverage

**Comment by javajolt** [comment]
:+1:

**Pull request merged**
