### PR TITLE
Remove test code for reformat-indexes command [JIRA: RIAK-3239]

### PR DESCRIPTION
**Pull request by nickelization**
This functionality is being removed. Once basho/riak_kv#1610 and basho/riak_ee#418 are merged, this PR should also be merged.

### CODE REVIEW

**Comment by hazen** [comment]
@nickelization We should remove this test from GiddyUp, too, right?

**Comment by hazen** [comment]
:+1:

**Comment by nickelization** [comment]
@javajolt Thanks for the review! And yeah, we should remove it from GiddyUp.

**Comment by bashopatricia** [comment]
create jira issue

**Comment by Basho-JIRA** [comment]
This was already reviewed and merged to develop on Jan 26: marking as closed. 

***[posted via JIRA by Nick Marino]***

**Pull request merged**
