### PR TITLE
test riakc_ts:list_keys/4 in ts_basic

### PR DESCRIPTION
**Pull request by hmmr**
With an effort to grow ts_basic into manageable state.

Depends on https://github.com/basho/riak_kv/pull/1268 (and PRs mentioned therein).

### CODE REVIEW

**Comment by lukebakken** [comment]
+1 from me, someone with more experience should also review.

**Comment by javajolt** [comment]
Can we hold off merging this? I'm reworking `riak_test` and this will likely cause a mess.  I'm using much more of the utilities for all tests.  Also, I'm thinking this one needs to be broken in to many tests as it is now far from basic.

**Comment by hmmr** [comment]
@javajolt ts_basic is pretty much self-contained and independent from all others. I mean it to be complementary to the ts_* ones. I wonder how we could clash on this?

**Comment by javajolt** [comment]
@hmmr ts_basic tries to cover ALL functionality in one test, which was my comment.  Let's merge it and I'll sort through the merge madness on my end.

**Comment by javajolt** [comment]
Looks like we still need to sort a few things:
```
ts_basic failed: {undef,[{riak_pb_ts_codec,encode_columnnames,[[]],[]},{riakc_ts_put_operator,serialize,3,[{file,"src/riakc_ts_put_operator.erl"},{line,34}]},{riakc_ts,put,4,[{file,"src/riakc_ts.erl"},{line,93}]},{ts_basic,confirm_put,2,[{file,"tests/ts_basic.erl"},{line,116}]},{ts_basic,confirm_all_from_node,4,[{file,"tests/ts_basic.erl"},{line,76}]},{ts_basic,run_tests,2,[{file,"tests/ts_basic.erl"},{line,65}]},{riak_test_runner,return_to_exit,3,[{file,"src/riak_test_runner.erl"},{line,159}]}]}
```

**Comment by DSomogyi** [comment]
RTS-606 will be used for this PR.

**Comment by javajolt** [comment]
Cool, new error:
```
{badarg,[{erlang,length,
                 [{1001,
                   <<"invalid_query: \nincompatible_type: field pooter2 with type varchar cannot be compared to type identifier in where clause.\nincompatible_type: field pooter1 with type varchar cannot be compared to type identifier in where clause.">>}],
```

**Comment by alexmoore** [comment]
Sweet!

**Comment by hmmr** [comment]
Missed a chunk when preparing last commit. Fixed, apologies.

**Comment by javajolt** [comment]
Still see this:
```
{badarg,[{erlang,length,
                 [{1001,
                   <<"invalid_query: \nincompatible_type: field pooter2 with type varchar cannot be compared to type identifier in where clause.\nincompatible_type: field pooter1 with type varchar cannot be compared to type identifier in where clause.">>}],
```

**Comment by javajolt** [comment]
```
Test Results:
ts_basic-riak_kv_bitcask_backend,riak_kv_eleveldb_backend: pass
---------------------------------------------
0 Tests Failed
1 Tests Passed
That's 100.0% for those keeping score
```

**Comment by javajolt** [comment]
:+1:

**Pull request merged**
