### PR TITLE
Coverage query test for TimeSeries

### PR DESCRIPTION
**Pull request by macintux**
* Test the new functionality that allows for subqueries to be executed individually
* Slightly extend functionality in `ts_util` to assist

### CODE REVIEW

**Comment by hmmr** [comment]
The source file name should probably be ts_A_coverage.erl, in line with other ts_* modules.

**Comment by javajolt** [comment]
@hmmr Still need to have that discussion with Gordon about test names

**Comment by lehoff** [comment]
+1

**Comment by hmmr** [comment]
@borshop merge

**Pull request merged**
