### PR TITLE
RTS-1065: Refactor rt_cascading

### PR DESCRIPTION
**Pull request by javajolt**
Based on discussions with @JeetKunDoug, we broke the one monolithic test into 10:
```

Test Results:
rt_cascading_mixed_clusters-bitcask   : pass
rt_cascading_ensure_ack-bitcask       : pass
rt_cascading_diamond-bitcask          : pass
rt_cascading_circle_and_spurs-bitcask : pass
rt_cascading_circle-bitcask           : pass
rt_cascading_big_circle-bitcask       : pass
rt_cascading_unacked_and_queue-bitcask: fail
rt_cascading_simple-bitcask           : pass
rt_cascading_pyramid-bitcask          : pass
rt_cascading_new_to_old-bitcask       : pass
---------------------------------------------
1 Tests Failed
9 Tests Passed
```
The one test which failed seems flappy, so we should work on making that more stable.  Tested against riak-2.0.7rc3.  Seems to be more stable against riak-2.0.6

Noticed:

- Test hangs simply waiting for all 6 nodes to come up:
`Waiting for services [riak_kv] to start on ['dev1@127.0.0.1','dev2@127.0.0.1','dev3@127.0.0.1','dev4@127.0.0.1','dev5@127.0.0.1','dev6@127.0.0.1'].`
- Test hangs waiting for leadership to change. I see where leader is polled, but never changed. `Badrpc during is_leader for 'dev3@127.0.0.1'. Error: {'EXIT',{noproc,{gen_server,call,[riak_core_cluster_manager,leader_node,infinity]}}}`
- The `repl_util:wait_for_reads/5` also hangs

### CODE REVIEW

**Comment by javajolt** [comment]
Amazingly, on a good day, it actually works relatively quickly:
```
Test Results:
rt_cascading_mixed_clusters-bitcask   : pass
rt_cascading_ensure_ack-bitcask       : pass
rt_cascading_diamond-bitcask          : pass
rt_cascading_circle_and_spurs-bitcask : pass
rt_cascading_circle-bitcask           : pass
rt_cascading_big_circle-bitcask       : pass
rt_cascading_unacked_and_queue-bitcask: pass
rt_cascading_simple-bitcask           : pass
rt_cascading_pyramid-bitcask          : pass
rt_cascading_new_to_old-bitcask       : pass
---------------------------------------------
0 Tests Failed
10 Tests Passed
That's 100.0% for those keeping score

real	29m59.295s
```

**Comment by mrallen1** [comment]
Addresses #935 RTS-1065

**Comment by mrallen1** [comment]
OK here's the failure pattern I see (when it fails):

```
10:54:10.921 [info] <0.306.0> Waiting for repl connection to cluster named "n456" on node 'dev1@127.0.0.1'
10:54:11.923 [info] <0.306.0> Waiting for repl connection to cluster named "n456" on node 'dev1@127.0.0.1'
10:54:12.927 [info] <0.306.0> Waiting for repl connection to cluster named "n456" on node 'dev1@127.0.0.1'
10:54:13.932 [info] <0.306.0> Waiting for repl connection to cluster named "n456" on node 'dev1@127.0.0.1'
10:54:14.937 [info] <0.306.0> Waiting for repl connection to cluster named "n456" on node 'dev1@127.0.0.1'
10:54:15.941 [info] <0.306.0> Waiting for repl connection to cluster named "n456" on node 'dev1@127.0.0.1'
10:54:16.945 [info] <0.306.0> Waiting for repl connection to cluster named "n456" on node 'dev1@127.0.0.1'
10:54:17.949 [info] <0.306.0> Waiting for repl connection to cluster named "n456" on node 'dev1@127.0.0.1'
10:54:18.955 [info] <0.306.0> Waiting for repl connection to cluster named "n456" on node 'dev1@127.0.0.1'
10:54:19.957 [info] <0.306.0> Waiting for repl connection to cluster named "n456" on node 'dev1@127.0.0.1'
10:54:20.038 [info] <0.306.0> Waiting for repl connection to cluster named "n123" on node 'dev4@127.0.0.1'
10:54:21.049 [info] <0.306.0> Waiting for repl connection to cluster named "n123" on node 'dev4@127.0.0.1'
10:54:21.125 [info] <0.306.0> ===== ensure_unacked_and_queue: unacked does not increase when there are skips =====
10:54:21.125 [info] <0.306.0> Writing 10000 keys to 'dev1@127.0.0.1', which should RT repl to 'dev4@127.0.0.1'
10:54:39.947 [info] <0.306.0> Reading 10000 keys written from 'dev4@127.0.0.1'
10:54:47.144 [debug] <0.306.0> wait_for_reads errors: 10000
10:54:55.340 [debug] <0.306.0> wait_for_reads errors: 10000
10:55:03.310 [debug] <0.306.0> wait_for_reads errors: 10000
10:55:11.522 [debug] <0.306.0> wait_for_reads errors: 10000
10:55:19.486 [debug] <0.306.0> wait_for_reads errors: 10000
10:55:27.345 [debug] <0.306.0> wait_for_reads errors: 10000
10:55:35.055 [debug] <0.306.0> wait_for_reads errors: 10000
10:55:42.728 [debug] <0.306.0> wait_for_reads errors: 10000
10:55:50.361 [debug] <0.306.0> wait_for_reads errors: 10000
10:55:57.994 [debug] <0.306.0> wait_for_reads errors: 10000
```

So there's some kind of race condition or flappy connection about repl and then the keys which have been written never get replicated to cluster B.

**Comment by mrallen1** [comment]
OK, so further investigation shows that the A cluster cannot find any valid endpoints on the B cluster. The A cluster continues to attempt to connect, but the B cluster continues to think everything is awesome, so it never does anything about the connection to A.

**Comment by javajolt** [comment]
Not sure if this is useful or not, but I did see
```
dev1/log/console.log:2016-04-22 17:49:13.881 [error] <0.2273.0> Supervisor riak_core_cluster_mgr_sup had child riak_core_connection_mgr started with riak_core_connection_mgr:start_link() at <0.2480.0> exit with reason {{{{badrecord,state},[{riak_core_cluster_mgr,handle_call,3,[{file,"src/riak_core_cluster_mgr.erl"},{line,304}]},{gen_server,handle_msg,5,[{fil
e,"gen_server.erl"},{line,585}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]},{gen_server,call,[{riak_core_cluster_manager,'dev3@127.0.0.1'},{get_known_ipaddrs_of_cluster,{name,"n456"}},30000]}},{gen_server,call,[riak_core_cluster_manager,{get_known_ipaddrs_of_cluster,{name,"n456"}},infinity]}} in context child_terminated
```
This might be why the other cluster could not be retrieved by `locate_endpoints`

**Comment by mrallen1** [comment]
@nickelization and @bsparrow435 and I talked about this some more. Two things about `rt_cascading_unacked_and_queue`:

1. We need to wait for leader convergence on the A and B sides of the cluster. We are going to use the minty fresh `repl_util:wait_until_leader_converge/1`
2. We need to make sure the post-commit hook for replication has been properly installed on each node on the A and B sides of the cluster.  We will use `rt:wait_until_bucket_props/3` to check for that condition. 

We think this will solve the race conditions we see. 

However, we still believe there there is a bug where the connection manager on the A side is losing its endpoints and can't seem to get them back from other members in the ring, which suggests we are losing that information before it can be added into the ring record and gossiped to other cluster members.

**Comment by javajolt** [comment]
@mrallen1 I tried using `repl_util:wait_until_leader_converge/1` but that did not seem to solve the problem.  I did not try the post-commit hook, trick however.

**Comment by javajolt** [comment]
@nickelization Interesting.  I tested your changes and they look good.  I was suspicious because you were testing for bucket properties on a bucket which had not yet been written to.  However, it looks like riak_core will return the default bucket properties if the bucket does not exists, which it does not yet in this case.

https://github.com/basho/riak_core/blob/2.1.1/src/riak_core_bucket.erl#L140-L143

Guessing that just means that replication is ready to go on the node, more than on any particular bucket.

**Comment by javajolt** [comment]
👍 9081781

**Comment by JeetKunDoug** [comment]
:+1: @javajolt great work on this - thanks for seeing it through to the end.

**Comment by mrallen1** [comment]
Yeah it is super awesome @javajolt thanks! @nickelization and @bsparrow435  thanks for your help too

**Pull request merged**
