### PR TITLE
ts_simple_query_buffers: disable query_orderby_{no_updates,expiring}

### PR DESCRIPTION
**Pull request by hmmr**
Depends on https://github.com/basho/riak_kv/pull/1549 and https://github.com/basho/riak-erlang-client/pull/337.

These test cases do no longer apply after changes in riak_kv to drop allow_qbuf_reuse flag.

### CODE REVIEW

**Comment by macintux** [comment]
Perhaps a missed dep bump somewhere, but seeing this:

```2016-11-29 15:21:18.230 [error] <0.1963.0> gen_fsm <0.1963.0> in state connected
 terminated with reason: {error,{case_clause,{tsqueryreq,{tsinterpolation,<<"\nc
reate table t1\n(a varchar not null,\n b varchar not null,\n c timestamp not nul
l,\n d varchar,\n e sint64,\n primary key ((a, b, quantum(c, 10, s)), a, b, c))"
>>,[]},false,undefined,false}},[{riak_kv_ttb_ts,decode,2,[{file,"src/riak_kv_ttb
_ts.erl"},{line,51}]},{riak_api_pb_server,connected,2,[{file,"src/riak_api_pb_se
rver.erl"},{line,219}]},{riak_api_pb_server,decode_buffer,2,[{file,"src/riak_api
_pb_server.erl"},{line,364}]},{gen_fsm,handle_msg,...},...]}
2016-11-29 15:21:18.230 [error] <0.1963.0> CRASH REPORT Process <0.1963.0> with
0 neighbours exited with reason: {error,{case_clause,{tsqueryreq,{tsinterpolatio
n,<<"\ncreate table t1\n(a varchar not null,\n b varchar not null,\n c timestamp
 not null,\n d varchar,\n e sint64,\n primary key ((a, b, quantum(c, 10, s)), a,
 b, c))">>,[]},false,undefined,false}},[{riak_kv_ttb_ts,decode,2,[{file,"src/ria
k_kv_ttb_ts.erl"},{line,51}]},{riak_api_pb_server,connected,2,[{file,"src/riak_a
pi_pb_server.erl"},{line,219}]},{riak_api_pb_server,decode_buffer,2,[{file,"src/riak_api_pb_server.erl"},{line,364}]},{gen_fsm,handle_msg,...},...]} in gen_fsm:terminate/7 line 622```

**Comment by hazen** [comment]
I got this from `riak_test`:
```
ts_simple_query_buffers_SUITE:init_per_suite failed
Reason: {badmatch,{error,<<"Error processing incoming me"...>>}}
```
And the same thing @macintux reported in the crash.log

**Comment by macintux** [comment]
riak_test has riak_pb pinned to a tag. Checking out develop fixed that for me.

**Comment by macintux** [comment]
+1

**Pull request merged**
