### PR TITLE
Changes for Riak Shell help in 1.5

### PR DESCRIPTION
**Pull request by andytill**

### CODE REVIEW

**Comment by hazen** [comment]
:+1:

**Comment by hazen** [comment]
@andytill It also occurs to me that https://github.com/basho/riak_shell/pull/71 will probably impact the text used in `ts_cluster_riak_shell_regression_log`.  Might want to sneak that in here, too.

**Comment by andytill** [comment]
That is what this change is.

**Comment by hazen** [comment]
LOL. You are right. :facepalm:

**Comment by hazen** [comment]
:+1:

**Pull request merged**
