### PR TITLE
Test of reporting TS errors of underlying atom type

### PR DESCRIPTION
**Pull request by paegun**
* added ts overload test to ensure errors reported as atoms, such as overload, are properly reported.

Depends on:
* https://github.com/basho/riak_kv/pull/1544

### CODE REVIEW

**Comment by hazen** [comment]
@paegun Would you mind renaming your test to match the naming convention, i.e., `ts_cluster_overload_reported`?

**Comment by paegun** [comment]
@javajolt renamed, thank you.

**Comment by hazen** [comment]
Test passes with the requisite KV changes

**Comment by hazen** [comment]
:+1:

**Pull request merged**
