### PR TITLE
Update Documentation and Build Scripts for Riak 2.1

### PR DESCRIPTION
**Pull request by javajolt**
Use the documented scripts now to build
- 1.4.12
- 2.0.2 (needed for specific tests)
- 2.0.4 (needed for specific tests)
- 2.0.6 
- current (develop)

### CODE REVIEW

**Comment by mrallen1** [comment]
:+1: 2ea13ff

**Comment by mrallen1** [comment]
@javajolt Getting a 301 in the build-releases script for kerl download

Here's the right URL: https://raw.githubusercontent.com/spawngrid/kerl/master/kerl

**Comment by javajolt** [comment]
Good catch, @mrallen1.  Because I already had Erlang installed it skipped that.  Fixing...

**Comment by mrallen1** [comment]
:+1: ff1f73c

**Pull request merged**
