### PR TITLE
Hopefully fix the disconnection issue in the riak667_mixed test

### PR DESCRIPTION
**Pull request by seancribbs**

### CODE REVIEW

**Comment by javajolt** [comment]
:+1: 2e7f093

**Comment by seancribbs** [comment]
This passes on the builder?

**Comment by javajolt** [comment]
@seancribbs This passed on my devrel version

**Comment by seancribbs** [comment]
Ok, but it passed on mine too before the change. That's why I ask.

**Comment by javajolt** [comment]
So this only fails on the builder?

**Pull request merged**
