### PR TITLE
Riak Test for `node_confirms` bucket property

### PR DESCRIPTION
**Pull request by russelldb**
Adds a test for the scenario described in the main KV pull request here:
https://github.com/basho/riak_kv/pull/1663

### CODE REVIEW

**Comment by ghost** [comment]
As with #1302 - the tests passed when merged or rebased onto develop-2.2.5 but only after applying the following patch 
[fix_riak_test.patch.txt](https://github.com/basho/riak_test/files/1830289/fix_riak_test.patch.txt)

**Comment by russelldb** [comment]
I'm just getting around to this, you mean running `make test` fails without that patch? Not the riak_tests themselves? Right?

If thats the case, then ideally you'd open a PR for that patch, we could merge it, then crack on and merge the riak-tests and get shipping

**Comment by ghost** [comment]
I'll test it again now,  I'm guessing it should work since you merged https://github.com/basho/riak_kv/pull/1666 (fix schema paths for make test)

**Comment by russelldb** [comment]
hol'up, let me try and get you in slack

**Comment by russelldb** [comment]
see #1303

**Comment by ghost** [comment]
This P/R looks good with either of our p/r  ( #1303 / #1304 ) merged before. +1 after merging one of the prerequisite p/r

**Review by ghost — APPROVED** [review]

**Pull request merged**
