### PR TITLE
update riak_shell/regression.log wrt timestamp conversions & expanded EXPLAIN

### PR DESCRIPTION
**Pull request by hmmr**
This PR updates Expected strings for query tabular output, which now feature ISO timestamp conversions and expanded EXPLAIN format.

As a bonus, an unrelated cosmetic change in ts_simple_insert_incorrect_columns (create initial table via a call to `riakc_ts:query(DDL)` rather than clunky two-step riak-admin command).

@javajolt or @macintux may be interested.

### CODE REVIEW

**Comment by javajolt** [comment]
Failure for `ts_simple_insert_incorrect_columns`:
```
11:48:24.226 [info] <0.310.0> INSERT INTO GeoCheckin (myfamily,myseries,time,weather,temperature) VALUES ('rubbish','family1','seriesX',1,'uenpamcp',-2.054747394455508e18)
11:48:24.399 [info] <0.310.0> Result is {error,<<"Error processing incoming message: error:function_clause:[{lists,zip,
                                                           [[{float,
                                                              -2.054747394455508e18}],
                                                            []],
                                                           [{file,\"lists.erl\"},
                                                            {line,372}]},
                                                          {lists,zip,2,
                                                           [{file,\"lists.erl\"},
                                                            {line,372}]},
                                                          {lists,zip,2,
                                                           [{file,\"lists.erl\"},                                                                                                   {line,372}]},
                                                          {riak_kv_ts_util,
                                                           row_timestamp_translation,
                                                           3,
                                                           [{file,
                                                             \"src/riak_kv_ts_util.erl\"},
                                                            {line,192}]},
                                                          {lists,map,2,
                                                           [{file,\"lists.erl\"},                                                                                                   {line,1224}]},
                                                          {riak_kv_ts_util,                                                                                                        build_sql_record_int,
                                                           3,
                                                           [{file,
                                                             \"src/riak_kv_ts_util.erl\"},
                                                            {line,120}]},
                                                          {riak_kv_ts_util,
                                                           build_sql_record,3,
                                                           [{file,
                                                             \"src/riak_kv_ts_util.erl\"},
                                                            {line,72}]},
                                                          {riak_kv_ts_svc,
                                                           decode_query,2,
                                                           [{file,
                                                             \"src/riak_kv_ts_svc.erl\"},
                                                            {line,102}]}]">>}
```

**Comment by javajolt** [comment]
Failures for `ts_cluster_riak_shell_regression_log`: 
```
11:52:15.699 [info] <0.486.0> Riak-shell tests: Match Failure
11:52:15.699 [info] <0.486.0> **************************************************************
11:52:15.699 [info] <0.486.0> Ran "regression_log \"priv/riak_shell/riak_shell_regression1.log\";":
11:52:15.699 [info] <0.486.0> Exp: No Regression Errors.
11:52:15.699 [info] <0.486.0> Got: Error: invalid function call : log_EXT:regression_log ["priv/riak_shell/riak_shell_regression1.log"]Type 'regression_log "myregresion.log" ;' to run a regression. This will replay the log and check the results are the same as the last time you ran it. Useful for smoke testing and stuff.
11:52:15.699 [info] <0.486.0> **************************************************************
```

**Comment by hmmr** [comment]
For that error, you need https://github.com/basho/riak_kv/pull/1460.

This PR only deals with regressions in ts_cluster_riak_shell_regression_log.

**Comment by javajolt** [comment]
But it also has changes to `tests/ts_simple_insert_incorrect_columns.erl`, too, right?

**Comment by hmmr** [comment]
Those are trivial changes, entirely unrelated to the subject matter of the test. They are included here because they are not worth a PR of their own. The proper fix for ts_simple_insert_incorrect_columns is in https://github.com/basho/riak_kv/pull/1460.

**Comment by javajolt** [comment]
`ts_simple_insert_incorrect_columns` now passes.  Seeing what's wrong with riak_shell...

**Comment by javajolt** [comment]
:+1: f998987

**Pull request merged**
