### PR TITLE
add some clarity to ordering of socket close and such

### PR DESCRIPTION
**Pull request by zeeshanlakhani**

### CODE REVIEW

**Comment by jvoegele** [comment]
@zeeshanlakhani: Are you waiting for review on this one? I've looked over it and don't have any concerns, but must admit that I don't fully understand the potential impact of reordering these operations.

**Comment by zeeshanlakhani** [comment]
@jvoegele yep, this needs review. Admittedly, there's not much impact here... but it does make the test cleaner.

**Comment by jvoegele** [comment]
:+1: 13408eb9e28dfbc13ca704c305e18e2d17952ec5

**Comment by jonmeredith** [comment]
@zeeshanlakhani @jvoegele good to merge or waiting for something else?
should this land in riak/2.0 as well, or just master?

**Comment by zeeshanlakhani** [comment]
@jonmeredith just needs quick review. I added more info about things in https://bashoeng.atlassian.net/browse/RIAK-2063. Yeah, I was going to backport this to riak/2.0 afterward.

**Comment by zeeshanlakhani** [comment]
@jonmeredith I'd also need to backport a couple tests to riak/2.0 as well. Will do that in one set of cherry-picks. Guessing I'll go riak/2.0 and merge-forward next time.

**Comment by zeeshanlakhani** [comment]
Ah, just saw @jvoegele's thumb :).

**Comment by jvoegele** [comment]
I need a more prominent thumb, apparently.

**Pull request merged**
