### PR TITLE
Re-add old kv679 test and add new test for further dataloss edge case

### PR DESCRIPTION
**Pull request by russelldb**
`kv679_dataloss_fb.erl` test was part of the original kv679 suite, but at the time of 2.1
it was put in it's own branch. See https://github.com/basho/riak_test/pull/719 for discussion and decision. In short, Riak Test is made up of passing tests,
and kv679_dataloss_fb.erl still failed. Adding this back to a
branch off develop as I know have a fix of this issue.

There is also a new test, `kv679_dataloss_fb2.erl`, that shows another dataloss edge case in riak, even in 2.1 with
per-key-actor-epochs enabled. The test is a little convoluted, and is
based on a quickcheck counter example, included in the riak_kv/test
directory. In short, both this test, and the other kv679_dataloss_fb
test, show that even with multiple replicas acking/storing, a single
disk error on a single replica is enough to cause acked writes to be
silently and permanently lost. For a replicated database, that is bad

### CODE REVIEW

**Comment by russelldb** [comment]
I'm going to be opening the PR against riak_kv that provides a fix for both these tests in a short while, and will edit to provide link when I do. In the meantime, feel free to run these against 2.1 and up.

**Comment by nickelization** [comment]
Both tests make sense, and I confirmed they both fail without basho/riak_kv#1643 and pass with it. Still reviewing the riak_kv PR, but the test PR looks good to me. Thanks, Russell!

**Comment by nickelization** [comment]
+1

**Comment by JeetKunDoug** [comment]
+1 - merging to fix `partition_repair` before next Giddyup run. Still need to add the two new tests to the Giddyup database.

**Pull request merged**
