### PR TITLE
Add separate test for AAE fullsync with bucket types.

### PR DESCRIPTION
**Pull request by cmeiklejohn**

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
@bsparrow435 Looking for review; obsoletes #770.

**Comment by bsparrow435** [comment]
Running locally now.

**Comment by bsparrow435** [comment]
passes with changes in repl 665 fails without.

**Comment by bsparrow435** [comment]
+1 b2942aa436d3c3138d52f983069b7f8a38b3b521

**Pull request merged**
