### PR TITLE
Removing obsolete repl_reduced test.

### PR DESCRIPTION
**Pull request by JeetKunDoug**
The feature for which it was written will never be shipped. Fixes BTA-167 and perhaps other intermittent failures, as this test would continue running after riak_test thought it had killed it.

### CODE REVIEW

**Comment by macintux** [comment]
Also need a database update, @JeetKunDoug is looking at that.

:+1:

**Comment by JeetKunDoug** [comment]
See https://github.com/basho/giddyup/pull/150 for related SQL update for giddyup.

**Comment by fadushin** [comment]
+1 ad91ce48b41c0b213db7c7963b306ea148f05702

**Comment by javajolt** [comment]
+1000 (for good measure)

**Pull request merged**
