### PR TITLE
Tests for querying deleted rows.

### PR DESCRIPTION
**Pull request by andytill**
Tests for this riak_kv PR https://github.com/basho/riak_kv/pull/1383

### CODE REVIEW

**Comment by javajolt** [comment]
```
Test Results:
ts_simple_aggregation-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                                 : fail
ts_simple_aggregation_fail-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                            : pass
ts_simple_aggregation_math-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                            : fail
ts_simple_api-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                                         : fail
ts_simple_create_table_already_created-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                : pass
ts_simple_create_table_dup_primary_key-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                : pass
ts_simple_create_table_no_primary_key-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                 : pass
ts_simple_create_table_not_null_pk_fields-riak_kv_bitcask_backend,riak_kv_eleveldb_backend             : pass
ts_simple_create_table_pass_1-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                         : pass
ts_simple_create_table_short_key-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                      : fail
ts_simple_create_table_split_key-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                      : pass
ts_simple_describe_table-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                              : fail
ts_simple_div_by_zero-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                                 : pass
ts_simple_get-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                                         : fail
ts_simple_get_not_found-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                               : pass
ts_simple_insert-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                                      : fail
ts_simple_insert_incorrect_columns-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                    : pass
ts_simple_latin1_create_table_not_allowed-riak_kv_bitcask_backend,riak_kv_eleveldb_backend             : pass
ts_simple_put-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                                         : pass
ts_simple_put_all_datatypes-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                           : pass
ts_simple_put_all_null_datatypes-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                      : pass
ts_simple_put_bad_date-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                                : pass
ts_simple_put_invalid_data-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                            : pass
ts_simple_put_non_existent_bucket-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                     : pass
ts_simple_select-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                                      : fail
ts_simple_select_compare_two_fields_not_allowed-riak_kv_bitcask_backend,riak_kv_eleveldb_backend       : pass
ts_simple_select_double_in_key-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                        : fail
ts_simple_select_incompatible_type_float_not_allowed-riak_kv_bitcask_backend,riak_kv_eleveldb_backend  : pass
ts_simple_select_incompatible_type_integer_not_allowed-riak_kv_bitcask_backend,riak_kv_eleveldb_backend: pass
ts_simple_select_missing_field_in_pk_not_allowed-riak_kv_bitcask_backend,riak_kv_eleveldb_backend      : pass
ts_simple_select_not_found-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                            : pass
ts_simple_select_unexpected_token_not_allowed-riak_kv_bitcask_backend,riak_kv_eleveldb_backend         : pass
ts_simple_select_where_has_no_lower_bounds_not_allowed-riak_kv_bitcask_backend,riak_kv_eleveldb_backend: pass
ts_simple_select_where_has_no_upper_bounds_not_allowed-riak_kv_bitcask_backend,riak_kv_eleveldb_backend: pass
ts_simple_single_key_ops-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                              : fail
ts_simple_unicode_create_table_not_allowed-riak_kv_bitcask_backend,riak_kv_eleveldb_backend            : pass
riak_shell_test_connecting-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                            : fail
riak_shell_test_connecting_error-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                      : fail
riak_shell_test_disconnecting-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                         : fail
riak_shell_test_reconnecting-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                          : fail
ts_cluster_activate_table_pass_1-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                      : pass
ts_cluster_aggregation-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                                : fail
ts_cluster_comprehensive-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                              : fail
ts_cluster_coverage-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                                   : fail
ts_cluster_create_table_pass_1-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                        : pass
ts_cluster_create_table_via_sql_SUITE-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                 : fail
ts_cluster_put_pass_1-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                                 : pass
ts_cluster_random_query_pass_eqc-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                      : fail
ts_cluster_riak_shell_basic_sql-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                       : fail
ts_cluster_riak_shell_regression_log-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                  : fail
ts_cluster_select_pass_1-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                              : fail
ts_cluster_select_pass_2-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                              : fail
ts_cluster_select_pass_3_sorted_on_key-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                : fail
ts_cluster_unicode-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                                    : fail
ts_degraded_activate_table_fail_1-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                     : pass
ts_degraded_aggregation-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                               : fail
ts_degraded_select_pass_1-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                             : fail
ts_degraded_select_pass_2-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                             : fail
ts_simple_activate_table_pass_1-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                       : pass
ts_simple_activate_table_pass_2-riak_kv_bitcask_backend,riak_kv_eleveldb_backend                       : pass
---------------------------------------------
28 Tests Failed
32 Tests Passed
That's 53.333333333333336% for those keeping score
```

**Comment by javajolt** [comment]
Not sure if these are directly related to the KV change, but I intend to find out.

**Comment by andytill** [comment]
@javajolt I have run some of these tests which have passed, do you have crash reports from the nodes or assertion failures from the tests?

**Comment by macintux** [comment]
:+1:

**Comment by javajolt** [comment]
@andytill Test failures were unrelated to this change

**Pull request merged**
